[package]
name = "load1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
bundler = {git = "https://github.com/weaveVM/bundler.git", branch = "main"}
dotenv = "0.15.0"
aws-sdk-s3 = "1.80.0"
aws-config = "1.6.1"
